# Resource to manage and keep all ingame constants
extends Resource
class_name CONSTANTS

enum MOUNT_SIZES {MAIN, HEAVY, AUX, MAIN_AUX, FLEX, SUPERHEAVY, INTEGRATED}
enum WEAPON_TYPES {RIFLE, MELEE, CANNON, LAUNCHER, NEXUS, CQB}
enum WEAPON_RANGE_TYPES {RANGE, LINE, CONE, BLAST, BURST}
enum DAMAGE_TYPES {KINETIC, EXPLOSIVE, ENERGY, BURN, HEAT}
